# fly.toml app configuration file generated for my-little-proxy on 2024-01-22T22:29:36-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-little-proxy"
primary_region = "sea"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
REWRITE_HOST_URL = "https://ifconfig.me"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
